=== codejovz/Desarrollo_aplicaciones_multiplataforma/1DAM/Lenguaje de marcas (web)/Tercer trimestre/Ejercicios_Hoja_6/Ejercicio1y2/facturas.dtd
<!ELEMENT facturas(factura*)>
<!ELEMENT factura (num_fac, cod_cliente, articulo+)>
<!ELEMENT articulo(cod_articulo,nom_articulo,cantidad,precio)>
<!ELEMENT num_fac(#PCDATA)>
<!ELEMENT cod_cliente(#PCDATA)>
<!ELEMENT cod_articulo(#PCDATA)>
<!ELEMENT nom_articulo(#PCDATA)>
<!ELEMENT cantidad(#PCDATA)>
<!ELEMENT precio(#PCDATA)>
<!ATTLIST factura facturaID CDATA #REQUIRED>

=== codejovz/Desarrollo_aplicaciones_multiplataforma/1DAM/Lenguaje de marcas (web)/Tercer trimestre/Ejercicios_Hoja_6/Ejercicio1y2/facturas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facturas SYSTEM "facturas.dtd">
<?xml-stylesheet type="text/css" href="facturas.css"?>
<!--AQUI SOLO EL XML-->

<facturas>
  <factura facturaID="F1">
    <num_fac>1</num_fac>
    <cod_cliente>0011</cod_cliente>
    <articulo>
      <cod_articulo>0001</cod_articulo>
      <nom_articulo>PAN</nom_articulo>
      <cantidad>2</cantidad>
      <precio>3</precio>
    </articulo>
  </factura>
  <factura facturaID="F2">
   <num_fac>2</num_fac>
   <cod_cliente>0055</cod_cliente>
   <articulo>
     <cod_articulo>0002</cod_articulo>
     <nom_articulo>AGUA</nom_articulo>
     <cantidad>4</cantidad>
     <precio>5</precio>
   </articulo>
  </factura>
  <factura facturaID="F3">
    <num_fac>3</num_fac>
    <cod_cliente>0045</cod_cliente>
    <articulo>
      <cod_articulo>0003</cod_articulo>
      <nom_articulo>COCACOLA</nom_articulo>
      <cantidad>1</cantidad>
      <precio>180</precio>
    </articulo>
  </factura>
</facturas>
