<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resultados [
  <!ELEMENT resultados (partido)*>
  <!ELEMENT partido (local , visitante)*>
  <!ELEMENT local (nombre | gol)*>
  <!ELEMENT visitante (nombre | gol)*>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT gol (#PCDATA)>
]>

<resultados>

  <partido>
    <local>
      <nombre>Nottingham Prisas</nombre>
      <gol>0</gol>
    </local>
    <visitante>
      <gol>1</gol>
      <nombre>Inter Mitente</nombre>
    </visitante>
  </partido>
  
   <partido>
    <local>
      <nombre>Vodka Juniors</nombre>
      <gol>3</gol>
    </local>
    <visitante>
      <gol>3</gol>
      <nombre>Sparta da Risa</nombre>
    </visitante>
  </partido>
  
   <partido>
    <local>
      <nombre>Water de Munich</nombre>
      <gol>4</gol>
    </local>
    <visitante>
      <gol>2</gol>
      <nombre>Esteaua no beberé</nombre>
    </visitante>
  </partido>

</resultados>