<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resultados [
<!ELEMENT resultados (partido)*>
<!ELEMENT partido (local, visitante)>
<!ELEMENT local (nombre)>
<!ELEMENT visitante (nombre)>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST local goles CDATA #REQUIRED>
<!ATTLIST visitante goles CDATA #REQUIRED>
]>

<resultados>

  <partido>
    <local goles="0">
      <nombre>Nothingham Prisas</nombre>
    </local>
    <visitante goles="1">
      <nombre>Inter Mitente</nombre>
    </visitante>
  </partido>
  
   <partido>
    <local goles="3">
      <nombre>Vodka Juniors</nombre>
    </local>
    <visitante goles="3">
      <nombre>Sparta da Risa</nombre>
    </visitante>
  </partido>
  
   <partido>
    <local goles="4">
      <nombre>Water de Munich</nombre>
    </local>
    <visitante goles="2">
      <nombre>Esteaua no beberé</nombre>
    </visitante>
  </partido>

</resultados>